@api = http://localhost:3000

########## CATEGORÍAS ##########

### Crear "Entradas"
# @name crearEntradas
POST {{api}}/menu/categories
Content-Type: application/json

{
  "nombre": "Entradas",
  "orden": 1
}

### Crear "Platos principales"
# @name crearPlatos
POST {{api}}/menu/categories
Content-Type: application/json

{
  "nombre": "Platos principales",
  "orden": 2
}

### Crear "Bebidas"
# @name crearBebidas
POST {{api}}/menu/categories
Content-Type: application/json

{
  "nombre": "Bebidas",
  "orden": 3
}

### Crear "Postres"
# @name crearPostres
POST {{api}}/menu/categories
Content-Type: application/json

{
  "nombre": "Postres",
  "orden": 4
}


### (Opcional) Listar categorías para verificar
GET {{api}}/menu/categories


### Variables de respuesta (se rellenan con los _id devueltos)
@idEntradas = {{crearEntradas.response.body.$._id}}
@idPlatos   = {{crearPlatos.response.body.$._id}}
@idBebidas  = {{crearBebidas.response.body.$._id}}
@idPostres  = {{crearPostres.response.body.$._id}}


########## ITEMS ##########

### Bruschettas (Entradas)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "{{idEntradas}}",
  "nombre": "Bruschettas",
  "descripcion": "Pan tostado con tomate, albahaca y oliva",
  "precio": 1200,
  "imageUrl": "https://pedido360-menu-images.s3.us-east-1.amazonaws.com/meef8bhv.png",
  "orden": 1
}

### Empanadas de carne (Entradas)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "{{idEntradas}}",
  "nombre": "Empanadas de carne",
  "descripcion": "Criollas horneadas con salsa de acompañamiento",
  "precio": 5000,
  "imageUrl": "https://pedido360-menu-images.s3.us-east-1.amazonaws.com/iuy7jq35.png",
  "orden": 2
}

### Milanesa napolitana (Platos principales)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "{{idPlatos}}",
  "nombre": "Milanesa napolitana",
  "descripcion": "Con salsa de tomate, jamón, queso y papas fritas",
  "precio": 2500,
  "imageUrl": "https://pedido360-assets.s3.us-east-1.amazonaws.com/menu/Milanesanapolitana-pp.jpg",
  "orden": 1
}

### Jarra de limonada (Bebidas)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "68ccbfe573b369be9cfab033",
  "nombre": "Jarra de limonada",
  "descripcion": "Limonada casera, 1 litro",
  "precio": 1800,
  "imageUrl": "https://pedido360-menu-images.s3.us-east-1.amazonaws.com/55s3nv8r.png",
  "orden": 1
}

### Coca-Cola (Bebidas)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "68ccbfe573b369be9cfab033",
  "nombre": "Coca-Cola",
  "descripcion": "Bebida gaseosa 354 ml",
  "precio": 1200,
  "imageUrl": "https://pedido360-menu-images.s3.us-east-1.amazonaws.com/xu086v89.png",
  "orden": 2
}

### Corona (Bebidas)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "68ccbfe573b369be9cfab033",
  "nombre": "Corona",
  "descripcion": "Cerveza rubia 355 ml en trago",
  "precio": 2000,
  "imageUrl": "https://pedido360-menu-images.s3.us-east-1.amazonaws.com/2kpglhep.png",
  "orden": 3
}

### Panqueques con dulce de leche (Postres)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "68ccbfec73b369be9cfab035",
  "nombre": "Panqueques con dulce de leche",
  "descripcion": "2 unidades con dulce de leche",
  "precio": 2800,
  "imageUrl": "https://pedido360-menu-images.s3.us-east-1.amazonaws.com/xoiylnqa.png",
  "orden": 1
}

### Churros con dulce de leche (Postres)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "68ccbfec73b369be9cfab035",
  "nombre": "Churros con dulce de leche",
  "descripcion": "Porción de 10 churros con dulce de leche para untar(opcional)",
  "precio": 2200,
  "imageUrl": "https://pedido360-menu-images.s3.us-east-1.amazonaws.com/fukq478v.png",
  "orden": 2
}

### Tiramisú (Postres)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "68ccbfec73b369be9cfab035",
  "nombre": "Tiramisú",
  "descripcion": "Clásico italiano",
  "precio": 3000,
  "imageUrl": "https://pedido360-menu-images.s3.us-east-1.amazonaws.com/zjonn8se.png",
  "orden": 3
}

### Chocotorta (Postres)
POST {{api}}/menu/items
Content-Type: application/json

{
  "categoria": "68ccbfec73b369be9cfab035",
  "nombre": "Chocotorta",
  "descripcion": "Porción individual",
  "precio": 3200,
  "imageUrl": "https://pedido360-menu-images.s3.us-east-1.amazonaws.com/plhppaws.png",
  "orden": 4
}


########## VERIFICACIONES ##########

### Listar todos los ítems
GET {{api}}/menu/items

### Filtrar ítems por categoría (Entradas)
GET {{api}}/menu/items?categoryId={{idEntradas}}

### Filtrar ítems por categoría (Platos principales)
GET {{api}}/menu/items?categoryId={{idPlatos}}

### Buscar por texto (subcadena, p.ej. 'mila' o 'empan')
GET {{api}}/menu/items?q=mila

