@api = http://localhost:3000

########## PEDIDOS ##########

GET {{api}}/pedido/6830b5d881811b409becb886/estado


### Obtener todos los pedidos
GET {{api}}/pedido

### Agregar un nuevo pedido
POST {{api}}/pedido
Content-Type: application/json

{
  "mesa": "68be07c42d05ca6bd25462d3",
  "mesero": "68be081c2d05ca6bd25462d6",
  "estado": "pendiente",
  "items": [
    { "nombre": "Milanesa", "precioUnitario": 2500, "cantidad": 2 },
    { "nombre": "Coca Cola", "precioUnitario": 1200, "cantidad": 1 }
  ]
}
###
POST {{api}}/pedido
Content-Type: application/json

{
  "mesa": "682fb720b9ac57a504b4a80f",
  "descripcion": "2 ñoquis al pesto y 1 vino",
  "mesero": "682fd05192eba7954ce4f6f1",
  "total": 2000,
  "estado": "pendiente"
}


### Editar un pedido existente
PUT {{api}}/pedido/68be09f9c1e36833d0fd9546
Content-Type: application/json

{
  "mesa": "68be07c42d05ca6bd25462d3",
  "mesero": "68be081c2d05ca6bd25462d6",
  "estado": "pendiente",
  "items": [
    { "nombre": "Milanesa", "precioUnitario": 2500, "cantidad": 2 }
  ]
}

### Eliminar un pedido
DELETE {{api}}/pedido/68be08a62d05ca6bd25462d9

### Obtener todos los pedidos por mesero
GET {{api}}/pedido/mesero/682fd05192eba7954ce4f6f1