@api = http://localhost:3000

### Obtener todos los usuarios
GET {{api}}/usuarios

### Obtener un usuario por ID
GET {{api}}/usuarios/68be081c2d05ca6bd25462d6

### Obtener un usuario por correo
GET {{api}}/usuarios/correo/ssofia.perez@example.com
### Agregar un nuevo usuario
POST {{api}}/usuarios
Content-Type: application/json

{
  "nombre": "Damian ",
  "correo": "Aadmin@example.com",
  "rol": "admin",
  "contra": "123456"
}

### Editar un usuario por ID
PUT {{api}}/usuarios/
Content-Type: application/json

{
  "nombre": "Juan Pérez Actualizado",
  "correo": "juan.perez@example.com",
  "rol": "admin"
}

### Eliminar un usuario por ID
DELETE {{api}}/usuarios/

####
POST {{api}}/usuarios/login
Content-Type: application/json

{
  "correo": "ssofia.perez@example.com",
  "contra": "123456"
}
